resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      # ref: refs/heads/<branch-name>  # for future testings on a branch of NSLS-II/profile-collection-ci
      endpoint: github

jobs:
- template: azure-linux.yml@templates  # Template reference
  parameters:
    beamline_acronym: <CHANGE>
