jobs:
- job: run_profile_collection_2021_1_0

  pool:
    vmImage: 'ubuntu-latest'

  displayName: "profile_collection (${{ parameters.beamline_acronym }}):"

  variables:
    - CAPROTO_COMMAND: "python -m caproto.ioc_examples.pathological.spoof_beamline"
    - CONDA_ENV_NAME: collection-2021-1.0
    # DOI: https://doi.org/10.5281/zenodo.4421721
    # URL: https://zenodo.org/record/4421721/files/collection-2021-1.0.tar.gz?download=1
    - ZENODO_ID: 4421721
    - MD5_CHECKSUM: 12fa67ad0ed60bc7eeac8a2765109ab4
    - template: .azure-templates/common-vars.yml

  strategy:
    matrix:
      collection_2021_1_0:
        OPHYD_CONTROL_LAYER: pyepics
        CONDA_CHANNEL_NAME: nsls2forge
        PYTHON_VERSION: 3.7
      # Commenting out caproto OPHYD_CONTROL_LAYER test due to
      # https://github.com/caproto/caproto/issues/696.
      # py37_caproto:
      #   OPHYD_CONTROL_LAYER: caproto
      #   CONDA_CHANNEL_NAME: nsls2forge
      #   PYTHON_VERSION: 3.7

  steps:

    # Check the env
    - template: .azure-templates/check-env.yml

    # TODO: uncomment the block below once all profile repos are
    # "profile_collection". Some of them are not compliant with the name and
    # single profile per repo approach. See the list of those below.
    # # Check the startup/ dir exists
    # - template: .azure-templates/check-startup-dir-exists.yml

    # Get pyOlog and databroker configs
    - template: .azure-templates/get-configs.yml

    # Prepare a test profile dir
    - template: .azure-templates/prepare-test-profile-dir.yml

    # Check services and system packages
    - template: .azure-templates/check-services-and-pkgs.yml

    # Start mongodb service
    - template: .azure-templates/start-mongo.yml

    # Start docker service
    # - template: .azure-templates/start-docker.yml

    # Download and install miniconda
    - template: .azure-templates/install-miniconda.yml

    # Create conda env
    - template: .azure-templates/create-conda-env-archive.yml

    # Perform beamline-specific actions
    - template: .azure-templates/bl-specific.yml

    # Optionally start caproto IOC and start IPython with startup files
    - template: .azure-templates/run-tests.yml

    # Display bluesky logs
    - template: .azure-templates/display-bluesky-logs.yml
