jobs:
- job: run_profile_collection_2019_3_0_1

  pool:
    vmImage: 'ubuntu-latest'

  displayName: "profile_collection (${{ parameters.beamline_acronym }}):"

  variables:
    - template: .azure-templates/common-vars.yml
    - name: CAPROTO_COMMAND
      value: "caproto-spoof-beamline"
    - name: CONDA_ENV_NAME
      value: collection-2019-3.0.1
    - name: PKG_NAME
      value: collection
    - name: PKG_VERSION
      value: 2019C3.0.1

  strategy:
    matrix:
      collection_2019_3_0_1:
        OPHYD_CONTROL_LAYER: pyepics
        CONDA_CHANNEL_NAME: lightsource2-tag
        PYTHON_VERSION: 3.7.5
      # pyepics_new_ch_py37:
      #   OPHYD_CONTROL_LAYER: pyepics
      #   CONDA_CHANNEL_NAME: nsls2forge
      #   PYTHON_VERSION: 3.7.5
      # caproto_old_ch_py37:
      #   OPHYD_CONTROL_LAYER: caproto
      #   CONDA_CHANNEL_NAME: lightsource2-tag
      #   PYTHON_VERSION: 3.7.5
      # caproto_new_ch_py37:
      #   OPHYD_CONTROL_LAYER: caproto
      #   CONDA_CHANNEL_NAME: nsls2forge
      #   PYTHON_VERSION: 3.7.5

  steps:

    # Check the env
    - template: .azure-templates/check-env.yml

    # TODO: uncomment the block below once all profile repos are
    # "profile_collection". Some of them are not compliant with the name and
    # single profile per repo approach. See the list of those below.
    # # Check the startup/ dir exists
    # - template: .azure-templates/check-startup-dir-exists.yml

    # Get pyOlog and databroker configs
    - template: .azure-templates/get-configs.yml

    # Prepare a test profile dir
    - template: .azure-templates/prepare-test-profile-dir.yml

    # Check services and system packages
    - template: .azure-templates/check-services-and-pkgs.yml

    # Start mongodb service
    - template: .azure-templates/start-mongo.yml

    # Download and install miniconda
    - template: .azure-templates/install-miniconda.yml

    # Create conda env
    - template: .azure-templates/create-conda-env-pkgs.yml

    # Perform beamline-specific actions
    - template: .azure-templates/bl-specific.yml

    # Start caproto IOC and start IPython with startup files
    - template: .azure-templates/run-tests.yml
